steps:
  - name: docker/compose:1.29.2
    args: ["-f", "docker-compose.ci.yaml", "up", "--abort-on-container-exit", "--exit-code-from", "backend"]

  - name: docker/compose:1.29.2
    args: ["-f", "docker-compose.ci.yaml", "down", "-v"]

  - name: gcr.io/cloud-builders/gsutil
    args:
      - cp
      - -r
      - Backend/coverage
      - gs://my-ci-artifacts/coverage/$BUILD_ID

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET