services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports:
      - "3000:8080" 
    environment:
      NODE_ENV: production
      PORT: 8080 # This must be the same as the exposed port in 'ports', the second part.
      DATABASE_URL: ${DATABASE_URL}
      TOKEN_ISSUER: ${TOKEN_ISSUER}
      JWT_SECRET: ${JWT_SECRET}
      JWT_KEY: ${JWT_KEY}

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "80:8080"
    environment:
      API_BASE_URL: http://localhost:3000/api